name: Download artifact
description: 'Download docker image created in secure-docker-build'

inputs:
  IMAGE_NAME:
    required: true
    type: string
  IMAGE_DIGEST:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ env.IMAGE_DIGEST }}
        path: ${{ runner.temp }}

    - name: Load image
      run:
        cat ${{ runner.temp }}/${{ env.IMAGE_DIGEST }}.tar | docker import - ${{ env.IMAGE_NAME }}
