name: Build, test, push to Dockerhub 

on:
  workflow_call:
    secrets:
      MERKELY_API_TOKEN:
        required: true
      DOCKER_PASS:
        required: true
      DOCKER_USER:
        required: true
    inputs:
      CIRCLE_BUILD_NUM:
        required: true
        type: string
      CIRCLE_BUILD_URL:
        required: true
        type: string
      BUILD_SCRIPT_NAME:
        required: true
        type: string
      tag:
        required: true
        type: string
      AWS_ACCOUNT_ID:
        required: true
        type: string
      AWS_REGION:
        required: true
        type: string
      ecr_registry:
        required: true
        type: string
      service_name:
        required: true
        type: string
      gh_actions_iam_role_name:
        required: true
        type: string

jobs:
  build:
    name: Build test publish
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ inputs.AWS_ACCOUNT_ID }}:role/${{ inputs.gh_actions_iam_role_name }}
          aws-region: ${{ inputs.AWS_REGION }}
          role-duration-seconds: 2400
          role-session-name: ${{ github.event.repository.name }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build test publish
        env:
          CIRCLECI: true
          MERKELY_API_TOKEN: ${{ secrets.MERKELY_API_TOKEN }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          CIRCLE_BUILD_NUM: ${{ inputs.CIRCLE_BUILD_NUM }}
          CIRCLE_BUILD_URL: ${{ inputs.CIRCLE_BUILD_URL }}
        run: |
          echo "${DOCKER_PASS}" | docker login --username "${DOCKER_USER}" --password-stdin
          ./${{ inputs.BUILD_SCRIPT_NAME }}
          docker tag cyberdojo/${{ inputs.service_name }}:${{ inputs.tag }} ${{ inputs.ecr_registry }}/${{ inputs.service_name }}:${{ inputs.tag }}
          docker push ${{ inputs.ecr_registry }}/${{ inputs.service_name }}:${{ inputs.tag }}
          docker logout
