name: Build and push to ECR

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      AWS_ACCOUNT_ID:
        required: true
        type: string
      AWS_REGION:
        required: true
        type: string
      registry:
        required: true
        type: string
      service_name:
        required: true
        type: string
      gh_actions_iam_role_name:
        required: true
        type: string
      docker_context:
        required: true
        type: string

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ inputs.AWS_ACCOUNT_ID }}:role/${{ inputs.gh_actions_iam_role_name }}
          aws-region: ${{ inputs.AWS_REGION }}
          role-duration-seconds: 2400
          role-session-name: ${{ github.event.repository.name }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v3
        env:
          IMAGE_NAME: ${{ inputs.registry }}/${{ inputs.service_name }}
        with:
          context: ${{ inputs.docker_context }}
          push: true
          tags: "${{ env.IMAGE_NAME }}:${{ inputs.tag }},${{ env.IMAGE_NAME }}:latest"
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:latest
          cache-to: type=inline,mode=max
          build-args: |
            COMMIT_SHA=${{ github.sha }}
