name: Build, test, push to Dockerhub 

on:
  workflow_call:
    secrets:
      MERKELY_API_TOKEN:
        required: true
      DOCKER_PASS:
        required: true
      DOCKER_USER:
        required: true

jobs:
  build:
    name: Build test publish
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Build test publish
        env:
          CIRCLECI: true
          MERKELY_API_TOKEN: ${{ secrets.MERKELY_API_TOKEN }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          CIRCLE_BUILD_NUM: ${{github.run_number}}
          CIRCLE_BUILD_URL: ${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}
        run: |
          echo "${DOCKER_PASS}" | docker login --username "${DOCKER_USER}" --password-stdin
          ./build_test_publish.sh
          docker logout
