name: Secure docker build

on:
  workflow_call:
    inputs:
      IMAGE_TAR_FILENAME:
        required: true
        type: string
      IMAGE_NAME:
        required: true
        type: string


jobs:
  docker-image-load:
    needs: []
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve Docker image from cache
        uses: actions/cache@v4
        with:
          path: ${{ inputs.IMAGE_TAR_FILENAME }}
          key:  ${{ inputs.IMAGE_NAME }}

      - name: Load Docker image
        run:
          docker image load 
            --input "${{ inputs.IMAGE_TAR_FILENAME }}"
