name: Deploy

on:
  workflow_call:
    secrets:
      KOSLI_API_TOKEN:
        required: true
    inputs:
      AWS_ACCOUNT_ID:
        required: true
        type: string
      AWS_REGION:
        required: true
        type: string
      cyber_dojo_env_name_aws:
        required: true
        type: string
      gh_actions_iam_role_name:
        required: true
        type: string
      kosli_host_production:
        required: true
        type: string
      kosli_host_staging:
        required: true
        type: string
      tagged_image:
        required: true
        type: string
      environment_name:
        required: true
        type: string
      environment_url:
        required: true
        type: string


jobs:
  report-expected-deployment:
    runs-on: ubuntu-20.04
    environment:
      name: ${{ inputs.environment_name }}
      url: ${{ inputs.environment_url }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 1

      - name: setup kosli
        uses: kosli-dev/setup-cli-action@v1
        with:
          version:
            2.0.0

      - name: Report expected deployment to Kosli
        env:
          CYBER_DOJO_ENV_NAME_AWS: ${{ inputs.cyber_dojo_env_name_aws }}
          KOSLI_API_TOKEN: ${{ secrets.KOSLI_API_TOKEN }}
          KOSLI_HOST_STAGING: ${{ inputs.kosli_host_staging }}
          KOSLI_HOST_PRODUCTION: ${{ inputs.kosli_host_production }}
          KOSLI_ORG: cyber-dojo
        run: |
          source ./sh/kosli.sh
          kosli_expect_deployment ${CYBER_DOJO_ENV_NAME_AWS} ${KOSLI_HOST_STAGING}
          kosli_expect_deployment ${CYBER_DOJO_ENV_NAME_AWS} ${KOSLI_HOST_PRODUCTION}

  deploy:
    needs: [ report-expected-deployment ]
    uses: fivexl/gh-workflow-tf-plan-apply/.github/workflows/base.yml@v0.0.7
    with:
      aws_region: ${{ inputs.AWS_REGION }}
      aws_role_arn: arn:aws:iam::${{ inputs.AWS_ACCOUNT_ID }}:role/${{ inputs.gh_actions_iam_role_name }}
      aws_default_region: ${{ inputs.AWS_REGION }}
      aws_role_duration: 900
      working_directory: deployment/terraform/
      tf_apply: 'true'
      tf_version: v1.4.5
      tf_additional_env_vars: '{"TF_VAR_TAGGED_IMAGE": "${{ inputs.tagged_image }}"}'
