name: Build, test, push to Dockerhub

on:
  workflow_call:
    secrets:
      DOCKER_PASS:
        required: true
      DOCKER_USER:
        required: true
      KOSLI_API_TOKEN:
        required: true
      KOSLI_API_TOKEN_STAGING:
        required: true
    inputs:
      BUILD_COMMAND:
        required: true
        type: string
      KOSLI_FLOW:
        required: true
        type: string

jobs:
  build:
    name: Build test publish
    runs-on: ubuntu-20.04
    permissions:
      id-token: write
      contents: write
    steps:

      - name: setup kosli
        uses: kosli-dev/setup-cli-action@v2
        with:
          version: ${{ vars.KOSLI_CLI_VERSION }}

      - name: setup Snyk
        uses: snyk/actions/setup@master

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build test publish
        env:
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          KOSLI_HOST_STAGING: https://staging.app.kosli.com
          KOSLI_HOST_PRODUCTION: https://app.kosli.com
          KOSLI_ORG: cyber-dojo
          KOSLI_API_TOKEN: ${{ secrets.KOSLI_API_TOKEN }}
          KOSLI_API_TOKEN_STAGING: ${{ secrets.KOSLI_API_TOKEN_STAGING }}
          KOSLI_FLOW: ${{ inputs.KOSLI_FLOW }}

        run: |
          ./${{ inputs.BUILD_COMMAND }}
          # echo "${DOCKER_PASS}" | docker login --username "${DOCKER_USER}" --password-stdin
          # docker push ${{ inputs.KOSLI_FLOW }}:${{ inputs.IMAGE_TAG }}
          # docker logout
