name: Deploy

on:
  workflow_call:
    secrets:
      KOSLI_API_TOKEN:
        required: true
      KOSLI_API_TOKEN_STAGING:
        required: true
    inputs:
      AWS_ACCOUNT_ID:
        required: true
        type: string
      AWS_REGION:
        required: true
        type: string
      cyber_dojo_env_name_aws:
        required: true
        type: string
      gh_actions_iam_role_name:
        required: true
        type: string
      kosli_host_production:
        required: true
        type: string
      kosli_host_staging:
        required: true
        type: string
      tagged_image:
        required: true
        type: string
      environment_name:
        required: true
        type: string
      environment_url:
        required: true
        type: string


jobs:
  pre-deployment:
    runs-on: ubuntu-20.04
    environment:
      name: ${{ inputs.environment_name }}
      url: ${{ inputs.environment_url }}
    steps:
        run:
          # Just to get environment:name and environment:url

  deploy:
    needs: [ report-expected-deployment ]
    permissions:
      id-token: write
      contents: write
    uses: fivexl/gh-workflow-tf-plan-apply/.github/workflows/base.yml@v0.0.7
    with:
      aws_region: ${{ inputs.AWS_REGION }}
      aws_role_arn: arn:aws:iam::${{ inputs.AWS_ACCOUNT_ID }}:role/${{ inputs.gh_actions_iam_role_name }}
      aws_default_region: ${{ inputs.AWS_REGION }}
      aws_role_duration: 900
      working_directory: deployment/terraform/
      tf_apply: 'true'
      tf_version: v1.4.5
      tf_additional_env_vars: '{"TF_VAR_TAGGED_IMAGE": "${{ inputs.tagged_image }}"}'
